# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='namedetails',
            field=models.CharField(default='abc', max_length=1000),
        ),
    ]
