# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0003_auto_20170610_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_detail', models.CharField(default='aaa', max_length=1000)),
                ('movie_pic_url', models.URLField()),
            ],
        ),
    ]
