# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0005_movie_movie_detail_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_detail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_detail_other',
            field=models.CharField(max_length=1000),
        ),
    ]
