# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0006_auto_20170617_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_detail',
            new_name='movie_guy',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_detail_other',
            new_name='movie_name',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='movie_pic_url',
            new_name='movie_pic',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_director',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_score',
            field=models.FloatField(default='1.1'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_score_img',
            field=models.URLField(default='dsdsdad'),
        ),
    ]
