# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0007_auto_20170617_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_director',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_score_img',
            field=models.URLField(),
        ),
    ]
